### ISSUE TITLE
Crash on Nexus 9 

### ISSUE THREAD

**Issue by saikrishna321** [thotegowda/KanJuice#1]
D/AndroidRuntime( 2184): Shutting down VM
E/AndroidRuntime( 2184): FATAL EXCEPTION: main
E/AndroidRuntime( 2184): Process: com.example.kanjuice, PID: 2184
E/AndroidRuntime( 2184): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.bluetooth.BluetoothAdapter.getBondedDevices()' on a null object reference
E/AndroidRuntime( 2184):    at com.example.kanjuice.BluetoothDataReader.findBT(BluetoothDataReader.java:71)
E/AndroidRuntime( 2184):    at com.example.kanjuice.BluetoothDataReader.openConnection(BluetoothDataReader.java:52)
E/AndroidRuntime( 2184):    at com.example.kanjuice.BluetoothReaderService$1.handleMessage(BluetoothReaderService.java:29)
E/AndroidRuntime( 2184):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2184):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2184):    at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 2184):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2184):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2184):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 2184):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager(  632):   Force finishing activity com.example.kanjuice/.JuiceMenuActivity
E/EGL_emulation(  669): tid 669: eglCreateSyncKHR(1181): error 0x3004 (EGL_BAD_ATTRIBUTE)
W/art     (  632): Long monitor contention event with owner method=android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplications(android.os.IBinder, int, int, int, boolean) from WindowManagerService.java:6033 waiters=0 for 378ms
W/art     (  632): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12038 waiters=0 for 382ms
W/art     (  632): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12038 waiters=1 for 354ms
I/OpenGLRenderer(  632): Initialized EGL, version 1.4
W/EGL_emulation(  632): eglSurfaceAttrib not implemented
W/OpenGLRenderer(  632): Failed to set EGL_SWAP_BEHAVIOR on surface 0x9f5cbd80, error=EGL_SUCCESS
W/ActivityManager(  632): Activity pause timeout for ActivityRecord{2dce4a11 u0 com.example.kanjuice/.JuiceMenuActivity t6 f}
W/EGL_emulation( 1434): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 1434): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa4407f20, error=EGL_SUCCESS
D/TaskPersister(  632): removeObsoleteFile: deleting file=5_task.xml
D/TaskPersister(  632): removeObsoleteFile: deleting file=5_task_thumbnail.png
W/ActivityManager(  632): Activity destroy timeout for ActivityRecord{2dce4a11 u0 com.example.kanjuice/.JuiceMenuActivity t6 f}
D/Retrofit( 2184): ---- ERROR http://10.132.127.212:8083/api/beverages/juices
D/Retrofit( 2184): java.net.SocketTimeoutException: failed to connect to /10.132.127.212 (port 8083) after 15000ms
D/Retrofit( 2184):  at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
D/Retrofit( 2184):  at libcore.io.IoBridge.connect(IoBridge.java:122)
D/Retrofit( 2184):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
D/Retrofit( 2184):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
D/Retrofit( 2184):  at java.net.Socket.connect(Socket.java:882)
D/Retrofit( 2184):  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
D/Retrofit( 2184):  at com.android.okhttp.Connection.connect(Connection.java:148)
D/Retrofit( 2184):  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
D/Retrofit( 2184):  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
D/Retrofit( 2184):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
D/Retrofit( 2184):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
D/Retrofit( 2184):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
D/Retrofit( 2184):  at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
D/Retrofit( 2184):  at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
D/Retrofit( 2184):  at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
D/Retrofit( 2184):  at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
D/Retrofit( 2184):  at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
D/Retrofit( 2184):  at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
D/Retrofit( 2184):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D/Retrofit( 2184):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D/Retrofit( 2184):  at java.lang.Thread.run(Thread.java:818)
D/Retrofit( 2184): ---- END ERROR
D/JuiceMenuActivity( 2184): Failed to fetch menu list : retrofit.RetrofitError: failed to connect to /10.132.127.212 (port 8083) after 15000ms

**Comment by dkurra** [comment]
Sai,

Connecting to  http://10.132.127.212:8083/api/beverages/juices is causing the error. 
This ip can be accessed only tw network.
